/**
 * Nsmf_PDUSession
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */

#include "SMContextsCollectionApi.h"

#include <cassert>
#include <cstring>
#include <cstdio>
#include <iostream>
#include <list>
#include <map>
#include <string>

#include "logger.hpp"
#include "Helpers.h"
#include "mime_parser.hpp"
#include "smf_config.hpp"

extern std::unique_ptr<oai::config::smf::smf_config> smf_cfg;

namespace oai {
namespace smf_server {
namespace api {

using namespace oai::model::common::helpers;
using namespace oai::model::smf;
using namespace oai::utils;

SMContextsCollectionApi::SMContextsCollectionApi(
    std::shared_ptr<Pistache::Rest::Router> rtr) {
  router = rtr;
}

void SMContextsCollectionApi::init() {
  setupRoutes();
}

void SMContextsCollectionApi::setupRoutes() {
  using namespace Pistache::Rest;

  Routes::Post(
      *router,
      base + oai::smf::api::smf_sbi_helper::SmfPduSessionPathSmContexts,
      Routes::bind(&SMContextsCollectionApi::post_sm_contexts_handler, this));

  // Default handler, called when a route is not found
  router->addCustomHandler(Routes::bind(
      &SMContextsCollectionApi::sm_contexts_collection_api_default_handler,
      this));
}

void SMContextsCollectionApi::post_sm_contexts_handler(
    const Pistache::Rest::Request& request,
    Pistache::Http::ResponseWriter response) {
  Logger::smf_api_server().debug("");
  Logger::smf_api_server().info(
      "Received a SM context create request from AMF.");
  SmContextMessage smContextMessage       = {};
  SmContextCreateData smContextCreateData = {};

  // Simple parser
  oai::utils::mime_parser sp = {};
  if (!sp.parse(request.body())) {
    response.send(Pistache::Http::Code::Bad_Request);
    return;
  }

  std::unordered_map<std::string, oai::utils::mime_part> parts = {};
  sp.get_mime_parts(parts);
  uint8_t size = parts.size();
  Logger::smf_api_server().debug("Number of MIME parts %d", size);
  // At least 2 parts for Json data and N1 (+ N2)
  if (size < 2) {
    response.send(Pistache::Http::Code::Bad_Request);
    return;
  }

  // Step 2. process the request
  try {
    nlohmann::json::parse(parts[oai::utils::JSON_CONTENT_ID_MIME].body.c_str())
        .get_to(smContextCreateData);
    smContextMessage.setJsonData(smContextCreateData);

    // Must include N1 NAS msg
    if (parts.count(oai::utils::N1_SM_CONTENT_ID) > 0) {
      smContextMessage.setBinaryDataN1SmMessage(
          parts[oai::utils::N1_SM_CONTENT_ID].body);
    } else {
      response.send(Pistache::Http::Code::Bad_Request);
      return;
    }

    this->post_sm_contexts(smContextMessage, response);

  } catch (nlohmann::detail::exception& e) {
    Logger::smf_api_server().warn(
        "Cannot parse the json data (error: %s)!", e.what());
    response.send(Pistache::Http::Code::Bad_Request, e.what());
    return;
  } catch (std::exception& e) {
    Logger::smf_api_server().warn("Error: %s!", e.what());
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
    return;
  }
}

void SMContextsCollectionApi::sm_contexts_collection_api_default_handler(
    const Pistache::Rest::Request&, Pistache::Http::ResponseWriter response) {
  response.send(
      Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}  // namespace api
}  // namespace smf_server
}  // namespace oai
