/**
 * Nsmf_PDUSession
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "DnnConfigurationMessage.h"

namespace oai {
namespace smf_server {
namespace model {

DnnConfigurationMessage::DnnConfigurationMessage() {}

DnnConfigurationMessage::~DnnConfigurationMessage() {}

void DnnConfigurationMessage::validate() {
  // TODO: implement validation
}

std::string DnnConfigurationMessage::getDnn() const {
  return m_Dnn;
}

void DnnConfigurationMessage::setDnn(std::string const& value) {
  m_Dnn = value;
}

Snssai DnnConfigurationMessage::getSnssai() const {
  return m_Snssai;
}

void DnnConfigurationMessage::setSnssai(Snssai const& value) {
  m_Snssai = value;
}

std::string DnnConfigurationMessage::getSupi() const {
  return m_Supi;
}

void DnnConfigurationMessage::setSupi(std::string const& value) {
  m_Supi      = value;
  m_SupiIsSet = true;
}

bool DnnConfigurationMessage::supiIsSet() const {
  return m_SupiIsSet;
}

std::string DnnConfigurationMessage::getPduSessionType() const {
  return m_PduSessionType;
}

void DnnConfigurationMessage::setPduSessionType(std::string const& value) {
  m_PduSessionType      = value;
  m_PduSessionTypeIsSet = true;
}

bool DnnConfigurationMessage::pduSessionTypeIsSet() const {
  return m_PduSessionTypeIsSet;
}

std::string DnnConfigurationMessage::getIpv4Range() const {
  return m_Ipv4Range;
}

void DnnConfigurationMessage::setIpv4Range(std::string const& value) {
  m_Ipv4Range      = value;
  m_Ipv4RangeIsSet = true;
}

bool DnnConfigurationMessage::ipv4RangeIsSet() const {
  return m_Ipv4RangeIsSet;
}

std::string DnnConfigurationMessage::getIpv6Prefix() const {
  return m_Ipv6Prefix;
}

void DnnConfigurationMessage::setIpv6Prefix(std::string const& value) {
  m_Ipv6Prefix      = value;
  m_Ipv6PrefixIsSet = true;
}

bool DnnConfigurationMessage::ipv6PrefixIsSet() const {
  return m_Ipv6PrefixIsSet;
}

void to_json(nlohmann::json& j, const DnnConfigurationMessage& o) {
  j           = nlohmann::json();
  j["dnn"]    = o.m_Dnn;
  j["snssai"] = o.m_Snssai;
  if (o.pduSessionTypeIsSet()) j["pduSessionType"] = o.m_PduSessionType;
  if (o.ipv4RangeIsSet()) j["ipv4Range"] = o.m_Ipv4Range;
  if (o.ipv6PrefixIsSet()) j["ipv6Prefix"] = o.m_Ipv6Prefix;
}

void from_json(const nlohmann::json& j, DnnConfigurationMessage& o) {
  j.at("dnn").get_to(o.m_Dnn);
  j.at("snssai").get_to(o.m_Snssai);

  if (j.find("pduSessionType") != j.end()) {
    j.at("pduSessionType").get_to(o.m_PduSessionType);
    o.m_PduSessionTypeIsSet = true;
  }
  if (j.find("ipv4Range") != j.end()) {
    j.at("ipv4Range").get_to(o.m_Ipv4Range);
    o.m_Ipv4RangeIsSet = true;
  }
  if (j.find("ipv6Prefix") != j.end()) {
    j.at("ipv6Prefix").get_to(o.m_Ipv6Prefix);
    o.m_Ipv6PrefixIsSet = true;
  }
}

}  // namespace model
}  // namespace smf_server
}  // namespace oai
