/**
 * Nsmf_EventExposure
 * Session Management Event Exposure Service. © 2019, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SmfEvent.h"
#include <iostream>
namespace oai {
namespace flexcn_server {
namespace model {

SmfEvent::SmfEvent() {}

SmfEvent::~SmfEvent() {}

void SmfEvent::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const SmfEvent& o) {
  j = nlohmann::json();
  j = o.event;
}

void from_json(const nlohmann::json& j, SmfEvent& o) {
    o.event = j.get<std::string>();
}

}  // namespace model
}  // namespace flexcn_server
}  // namespace oai
