/**
 * Nsmf_EventExposure
 * Session Management Event Exposure Service. © 2019, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */

#include "IndividualSubscriptionDocumentApiImpl.h"

namespace oai {
namespace smf_server {
namespace api {

using namespace oai::model::smf;

IndividualSubscriptionDocumentApiImpl::IndividualSubscriptionDocumentApiImpl(
    std::shared_ptr<Pistache::Rest::Router> rtr,
    oai::app::smf::smf_app* smf_app_inst, std::string address)
    : IndividualSubscriptionDocumentApi(rtr),
      m_smf_app(smf_app_inst),
      m_address(address) {}

void IndividualSubscriptionDocumentApiImpl::delete_individual_subcription(
    const std::string& subId, Pistache::Http::ResponseWriter& response) {
  Logger::smf_api_server().info(
      "IndividualSubscriptionDocumentApiImpl::delete_individual_subcription.."
      ".");
  response.send(
      Pistache::Http::Code::Not_Implemented,
      "delete_individual_subcription API has not been implemented yet!\n");
}
void IndividualSubscriptionDocumentApiImpl::get_individual_subcription(
    const std::string& subId, Pistache::Http::ResponseWriter& response) {
  Logger::smf_api_server().info(
      "IndividualSubscriptionDocumentApiImpl::get_individual_subcription...");
  response.send(
      Pistache::Http::Code::Not_Implemented,
      "get_individual_subcription API has not been implemented yet!\n");
}
void IndividualSubscriptionDocumentApiImpl::replace_individual_subcription(
    const std::string& subId, const NsmfEventExposure& nsmfEventExposure,
    Pistache::Http::ResponseWriter& response) {
  Logger::smf_api_server().info(
      "IndividualSubscriptionDocumentApiImpl::replace_individual_subcription.."
      ".");
  response.send(
      Pistache::Http::Code::Not_Implemented,
      "replace_individual_subcription API has not been implemented yet!\n");
}

}  // namespace api
}  // namespace smf_server
}  // namespace oai
