/**
 * Nsmf_PDUSession
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */

#include "IndividualPDUSessionHSMFApiImpl.h"

namespace oai {
namespace smf_server {
namespace api {

using namespace oai::model::smf;

IndividualPDUSessionHSMFApiImpl::IndividualPDUSessionHSMFApiImpl(
    std::shared_ptr<Pistache::Rest::Router> rtr,
    oai::app::smf::smf_app* smf_app_inst, std::string address)
    : IndividualPDUSessionHSMFApi(rtr),
      m_smf_app(smf_app_inst),
      m_address(address) {}

void IndividualPDUSessionHSMFApiImpl::release_pdu_session(
    const std::string& pduSessionRef, const ReleaseData& releaseData,
    Pistache::Http::ResponseWriter& response) {
  Logger::smf_api_server().info("release_pdu_session...");
  response.send(
      Pistache::Http::Code::Not_Implemented,
      "Release_pdu_session API has not been implemented yet!\n");
}
void IndividualPDUSessionHSMFApiImpl::update_pdu_session(
    const std::string& pduSessionRef, const HsmfUpdateData& hsmfUpdateData,
    Pistache::Http::ResponseWriter& response) {
  Logger::smf_api_server().info("update_pdu_session...");
  response.send(
      Pistache::Http::Code::Not_Implemented,
      "Update_pdu_session API has not been implemented yet!\n");
}

}  // namespace api
}  // namespace smf_server
}  // namespace oai
