/**
 * Nsmf_EventExposure
 * Session Management Event Exposure Service. © 2019, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */

/*
 * IndividualSubscriptionDocumentApiImpl.h
 *
 *
 */

#ifndef INDIVIDUAL_SUBSCRIPTION_DOCUMENT_API_IMPL_H_
#define INDIVIDUAL_SUBSCRIPTION_DOCUMENT_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <IndividualSubscriptionDocumentApi.h>

#include <pistache/optional.h>

#include "NsmfEventExposure.h"
#include "ProblemDetails.h"
#include "smf_app.hpp"
#include <string>

namespace oai {
namespace smf_server {
namespace api {

using namespace oai::model::smf;

class IndividualSubscriptionDocumentApiImpl
    : public oai::smf_server::api::IndividualSubscriptionDocumentApi {
 public:
  IndividualSubscriptionDocumentApiImpl(
      std::shared_ptr<Pistache::Rest::Router>,
      oai::app::smf::smf_app* smf_app_inst, std::string address);
  ~IndividualSubscriptionDocumentApiImpl() {}

  void delete_individual_subcription(
      const std::string& subId, Pistache::Http::ResponseWriter& response);
  void get_individual_subcription(
      const std::string& subId, Pistache::Http::ResponseWriter& response);
  void replace_individual_subcription(
      const std::string& subId, const NsmfEventExposure& nsmfEventExposure,
      Pistache::Http::ResponseWriter& response);

 private:
  oai::app::smf::smf_app* m_smf_app;
  std::string m_address;
};

}  // namespace api
}  // namespace smf_server
}  // namespace oai

#endif
