/**
 * Nsmf_PDUSession
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */

/*
 * IndividualSMContextApiImpl.h
 *
 *
 */

#ifndef INDIVIDUAL_SM_CONTEXT_API_IMPL_H_
#define INDIVIDUAL_SM_CONTEXT_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <IndividualSMContextApi.h>

#include <pistache/optional.h>

#include "ProblemDetails.h"
#include "SmContextReleaseData.h"
#include "SmContextRetrieveData.h"
#include "SmContextRetrievedData.h"
#include "SmContextUpdateData.h"
#include "SmContextUpdateError.h"
#include "SmContextUpdatedData.h"
#include "SmContextUpdateMessage.h"
#include "SmContextReleaseMessage.h"
#include <string>
#include "smf_app.hpp"

namespace oai {
namespace smf_server {
namespace api {

using namespace oai::model::smf;

class IndividualSMContextApiImpl
    : public oai::smf_server::api::IndividualSMContextApi {
 public:
  IndividualSMContextApiImpl(
      std::shared_ptr<Pistache::Rest::Router>,
      oai::app::smf::smf_app* smf_app_inst, std::string address);
  ~IndividualSMContextApiImpl() {}

  void release_sm_context(
      const std::string& smContextRef,
      const SmContextReleaseMessage& smContextReleaseMessage,
      Pistache::Http::ResponseWriter& response);
  void retrieve_sm_context(
      const std::string& smContextRef,
      const SmContextRetrieveData& smContextRetrieveData,
      Pistache::Http::ResponseWriter& response);
  void update_sm_context(
      const std::string& smContextRef,
      const SmContextUpdateMessage& smContextUpdateMessage,
      Pistache::Http::ResponseWriter& response);

 private:
  oai::app::smf::smf_app* m_smf_app;
  std::string m_address;

 protected:
};

}  // namespace api
}  // namespace smf_server
}  // namespace oai

#endif
