/**
 * Nsmf_PDUSession
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */

/*
 * SMContextsCollectionApiImpl.h
 *
 *
 */

#ifndef SM_CONTEXTS_COLLECTION_API_IMPL_H_
#define SM_CONTEXTS_COLLECTION_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <SMContextsCollectionApi.h>

#include <pistache/optional.h>

#include "SmContextMessage.h"
#include "ProblemDetails.h"
#include "SmContextCreateError.h"
#include "SmContextCreatedData.h"
#include "smf_app.hpp"

namespace oai {
namespace smf_server {
namespace api {

using namespace oai::model::smf;

class SMContextsCollectionApiImpl
    : public oai::smf_server::api::SMContextsCollectionApi {
 public:
  SMContextsCollectionApiImpl(
      std::shared_ptr<Pistache::Rest::Router>,
      oai::app::smf::smf_app* smf_app_inst, std::string address);
  ~SMContextsCollectionApiImpl() {}

  void post_sm_contexts(
      const SmContextMessage& smContextMessage,
      Pistache::Http::ResponseWriter& response);

 private:
  oai::app::smf::smf_app* m_smf_app;
  std::string m_address;

 protected:
};

}  // namespace api
}  // namespace smf_server
}  // namespace oai

#endif
